import img1 from '../../img/1.jpg';
const datalifestyle = [
    {
        id: 1,
        img: img1,
        category: "Arts & Culture",
        name: 'On World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    },
    {
        id: 2,
        img: img1,
        category: "Arts & Culture",
        name: 'On World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    }, {
        id: 3,
        img: img1,
        category: "Arts & Culture",
        name: 'On World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    }, {
        id: 4,
        img: img1,
        category: "Arts ",
        name: 'An World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    }, {
        id: 5,
        img: img1,
        category: "Culture",
        name: 'On World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    },
    {
        id: 6,
        img: img1,
        category: "Arts & Culture",
        name: 'On World Art Day, try out this activity for the whole family',
        date: 'March 21, 2020',
        content: 'Today’s freebie is a set of 60 beautiful multimedia icons designed by Carlotta Govi',
        link: 'Read the artcile',
    },
];
export default datalifestyle;